"""Public API for importing and normalizing supported tournament brackets."""

from .service import (
    CAPABILITIES,
    BracketImport,
    BracketLink,
    BracketProvider,
    CharacterEvidence,
    ImportedCharacter,
    ImportedMember,
    ImportedPlayer,
    ProviderCapabilities,
    fetch_challonge,
    fetch_parrygg,
    fetch_startgg,
    identify_bracket_link,
    parse_challonge,
    parse_parrygg,
    parse_startgg,
    parse_tonamel,
)

__all__ = [
    "CAPABILITIES",
    "BracketImport",
    "BracketLink",
    "BracketProvider",
    "CharacterEvidence",
    "ImportedCharacter",
    "ImportedMember",
    "ImportedPlayer",
    "ProviderCapabilities",
    "fetch_challonge",
    "fetch_parrygg",
    "fetch_startgg",
    "identify_bracket_link",
    "parse_challonge",
    "parse_parrygg",
    "parse_startgg",
    "parse_tonamel",
]
